apiVersion: v1
kind: Service
metadata:
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: nginx-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: nginx-project